<<<<<<< HEAD
name: "James Clegg"
description: "Teaching materials"

#url: "http://jameshclegg.github.io/GitHubPagesProj1"
url: "http://localhost:4000"

#paginate: 10

#markdown: rdiscount
permalink: pretty
pygments: true
=======
server: true
permalink: /:year/:title/
>>>>>>> tutsplus
